### PR TITLE
Bulk load function for all data of one genome annotation.

### PR DESCRIPTION
**Pull request by rsutormin**
This is beginning of discussion about support of load of all data related to one particular genome annotation. I'm going to propose implementation later on but let's reach an agreement for API function spec first.

### CODE REVIEW

**Comment by mlhenderson** [comment]
I don't understand what gene_type, mrna_type, cds_type are providing in the output?
Aren't they also in feature_types?  Also load_genes, load_mrnas, load_cdss?  Why those _and_ load_features_by_type?  Do you just want a way to turn off everything but gene, mrna, cds?

The method name could be 'get_combined_data'.
The data should not be called 'Genome_data', since this type only includes the annotation.
Maybe 'GenomeAnnotation_data'.

Name changes for inputs:

type_to_id_to_feature -> features_by_type
cds_id_to_protein -> proteins_by_cds_id
gene_id_to_mrna_ids -> mrna_ids_by_gene_id
gene_id_to_cds_ids -> cds_ids_by_gene_id
mrna_id_to_cds_ids -> cds_ids_by_mrna_id
mrna_id_to_exons -> exons_by_mrna_id
mrna_id_to_utr_type_to_utr -> utrs_by_utr_type_by_mrna_id

load_<X> should be either include_<X> if you want it True by default, or exclude_<X> if False by default.

**Comment by rsutormin** [comment]
@mlhenderson: I made all changes you suggested to do. Can you review the PR again?

**Comment by rsutormin** [comment]
@mlhenderson: wait, I'll add warning for large datasets.

**Comment by rsutormin** [comment]
@mlhenderson: Done.

**Pull request merged**
